version: "3.7"

services:
  app:
    build: .
    ports:
      - "9090:80"  # Alterado para mapear a porta 9090 do host para a porta 80 do contêiner Vue
    networks:
      - agendame-app

  nginx:
    image: nginx:alpine
    ports:
      - "90:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - agendame-app

networks:
  agendame-app:
    driver: bridge
